## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
type_counts = application_df['APPLICATION_TYPE'].value_counts()
type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
#scratch work
type_counts.iloc[8:]

T9     156
T13     66
T12     27
T2      16
T25      3
T14      3
T29      2
T15      2
T17      1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
#scratch work
replace_list = list(type_counts.iloc[8:].index)
replace_list

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(type_counts.iloc[8:].index)
cutoff_value = 528


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classification_types = application_df['CLASSIFICATION'].value_counts()
classification_types

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_cleaned = classification_types.loc[classification_types > 1]
classifications_cleaned

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
#scratch work
classification_types.iloc[5:].index

Index(['C7000', 'C1700', 'C4000', 'C5000', 'C1270', 'C2700', 'C2800', 'C7100',
       'C1300', 'C1280', 'C1230', 'C1400', 'C7200', 'C2300', 'C1240', 'C8000',
       'C7120', 'C1500', 'C1800', 'C6000', 'C1250', 'C8200', 'C1238', 'C1278',
       'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600',
       'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256',
       'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150'],
      dtype='object')

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_types.iloc[5:].index)
cutoff_value_classifications = 1883

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# View df
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [13]:
#View df data type
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [14]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies = pd.get_dummies(application_df)
dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [15]:
# Split our preprocessed data into our features and target arrays
y = dummies['IS_SUCCESSFUL'].values
X = dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                440

 dense_1 (Dense)             (None, 5)                 55

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 501
Trainable params: 501
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6129 - accuracy: 0.6822
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.7251
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7277
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7307
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7309
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5536 - accuracy: 0.7315
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5527 - accuracy: 0.7326
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5520 - accuracy: 0.7326
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7325
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7324
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7325
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7329
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7329
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7327
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7324
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7336
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7326
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7341
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7342
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7343
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7346
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7340
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7347
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7348
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7346
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7352
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7342
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7345
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7339
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7346
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7341
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7349
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7351
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7349
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7349
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7352
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7351
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7350
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7351
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7353
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7352
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7348
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7356
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7356
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7344
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7356
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7353
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7348
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7355
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7353
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7350
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7360
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7353
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7355
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7354
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7353
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7361
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7353
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7364
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7355
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7354
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7360
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7355
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7359
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7348
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7357
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7358
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7357
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7353
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7361
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7358
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7354
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7355
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7350
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7364
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7365
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7355
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7365
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7359
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7356
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7365
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7372
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7360
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7365
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7362
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7369
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7366
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7363
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7367
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7372
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7366
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7369
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7373
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7370
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7368
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7369
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7366
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7371
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7370
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7364

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5520 - accuracy: 0.7272 - 474ms/epoch - 2ms/step
Loss: 0.5519595742225647, Accuracy: 0.7272303104400635

In [21]:
# (SECOND ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 20
hidden_nodes_layer2 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 20)                880

 dense_4 (Dense)             (None, 20)                420

 dense_5 (Dense)             (None, 1)                 21

=================================================================
Total params: 1,321
Trainable params: 1,321
Non-trainable params: 0
_________________________________________________________________

In [22]:

# Compile the model (SECOND ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:

# Train the model (SECOND ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5831 - accuracy: 0.7133
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7283
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5539 - accuracy: 0.7311
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7320
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7330
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7333
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7348
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7349
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7340
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7356
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7350
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7345
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7347
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7353
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7352
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7344
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7353
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7366
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7352
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7367
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7365
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7373
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7358
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7364
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7370
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7368
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7370
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7358
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7371
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7364
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5425 - accuracy: 0.7368
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7367
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7380
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7385
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7371
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7375
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7374
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7372
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7383
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7379
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7386
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7386
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7384
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7383
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7386
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7371
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7381
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7383
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7384
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7377
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7383
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7393
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7388
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7387
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7393
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7373
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5399 - accuracy: 0.7391
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7379
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7391
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7380
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7390
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7385
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7378
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7383
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7385
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7395
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7385
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7393
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7394
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7394
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7396
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7397
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7394
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7383
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7389
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7387
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7398
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7387
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7389
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7390
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7391
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7398
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7392
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7397
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7393
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7393
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7394
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7397
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7394
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7391
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7394
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7399
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7391
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7398
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7394
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7405
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7392
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7399
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7403
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7394

In [24]:

# Evaluate the model using the test data (SECOND ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5570 - accuracy: 0.7247 - 434ms/epoch - 2ms/step
Loss: 0.5569559335708618, Accuracy: 0.7246647477149963

In [28]:
# (THIRD ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 30
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="relu"))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 30)                1320

 dense_13 (Dense)            (None, 30)                930

 dense_14 (Dense)            (None, 1)                 31

=================================================================
Total params: 2,281
Trainable params: 2,281
Non-trainable params: 0
_________________________________________________________________

In [30]:
# Compile the model (THIRD ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [31]:
# Train the model (THIRD ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6825 - accuracy: 0.6862
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6291 - accuracy: 0.6987
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5822 - accuracy: 0.7157
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7247
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5616 - accuracy: 0.7276
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5589 - accuracy: 0.7290
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5716 - accuracy: 0.7220
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7291
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7310
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7322
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7336
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5829 - accuracy: 0.7271
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5564 - accuracy: 0.7324
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5562 - accuracy: 0.7340
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5563 - accuracy: 0.7331
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7341
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7311
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5671 - accuracy: 0.7302
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7297
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7348
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6278 - accuracy: 0.7056
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5598 - accuracy: 0.7321
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5551 - accuracy: 0.7331
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5523 - accuracy: 0.7340
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7357
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7363
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7350
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5904 - accuracy: 0.7079
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7267
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7353
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7352
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7359
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7362
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7359
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7329
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5498 - accuracy: 0.7359
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7341
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5653 - accuracy: 0.7284
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7356
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5541 - accuracy: 0.7357
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7352
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7353
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7346
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7334
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5520 - accuracy: 0.7360
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7310
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7358
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5583 - accuracy: 0.7268
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7356
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7334
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7357
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7358
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7352
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7365
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7353
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5798 - accuracy: 0.7253
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5490 - accuracy: 0.7367
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7364
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7351
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7323
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7364
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5518 - accuracy: 0.7367
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7371
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7363
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5520 - accuracy: 0.7375
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7360
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7361
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5526 - accuracy: 0.7349
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7329
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7363
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7375
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7364
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6107 - accuracy: 0.7106
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5535 - accuracy: 0.7315
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7366
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7365
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7361
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7379
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7371
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7360
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7340
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7367
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7362
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7371
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7371
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7381
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7384
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5938 - accuracy: 0.7097
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7243
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7314
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7334
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7335
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7343
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7342
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7356
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7378
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7382
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7389
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7373
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7376

In [32]:

# Evaluate the model using the test data (THIRD ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5670 - accuracy: 0.7254 - 1s/epoch - 4ms/step
Loss: 0.5670331120491028, Accuracy: 0.7253644466400146

In [37]:
# Export our model to HDF5 file
filepath = r"AlphabetSoupCharity.h5"
nn.save(filepath, save_format='h5')